// <auto-generated />
using System;
using EFCore_Inheritance_Demo_Main9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Inheritance_Demo_Main9.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250822072227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.LogInfo", b =>
                {
                    b.Property<long>("LogInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogInfoId"));

                    b.Property<DateTime?>("LogInfoDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogInfoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogInfoUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogInfoId");

                    b.ToTable("LogInfoes");
                });

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCar", b =>
                {
                    b.Property<long>("carId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("carId"));

                    b.Property<string>("carName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carPrice")
                        .HasColumnType("int");

                    b.Property<int>("carYear")
                        .HasColumnType("int");

                    b.HasKey("carId");

                    b.ToTable("TPTCars");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", b =>
                {
                    b.HasBaseType("EFCore_Inheritance_Demo_Main9.Models.TPTCar");

                    b.Property<string>("carModel")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TPTCarModel");
                });

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", b =>
                {
                    b.HasOne("EFCore_Inheritance_Demo_Main9.Models.TPTCar", null)
                        .WithOne()
                        .HasForeignKey("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", "carId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
