// <auto-generated />
using EFCore_Inheritance_Demo_Main9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Inheritance_Demo_Main9.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250820122327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("carName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carPrice")
                        .HasColumnType("int");

                    b.Property<int>("carYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TPTCars");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", b =>
                {
                    b.HasBaseType("EFCore_Inheritance_Demo_Main9.Models.TPTCar");

                    b.Property<string>("carModel")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TPTCarModel");
                });

            modelBuilder.Entity("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", b =>
                {
                    b.HasOne("EFCore_Inheritance_Demo_Main9.Models.TPTCar", null)
                        .WithOne()
                        .HasForeignKey("EFCore_Inheritance_Demo_Main9.Models.TPTCarModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
